name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH=$PATH:/usr/bin:/usr/local/bin
            cd /home/oli40/web/breidfjord.com/public_html
            git fetch origin
            git reset --hard origin/main
            rm -rf node_modules
            npm install
            npm run build